export const ADD_TO_HISTORY = "TERMINAL/ADD_TO_HISTORY";
export const REMOVE_FROM_HISTORY = "TERMINAL/REMOVE_FROM_HISTORY";

export const ADD_CURRENT_COMAND = "TERMINAL/ADD_CURRENT_COMAND";
export const REMOVE_CURRENT_COMAND = "TERMINAL/REMOVE_CURRENT_COMAND";

export const ADD_COMAND = "TERMINAL/ADD_COMAND";

export const ADD_PREV_COMAND = "TERMINAL/ADD_PREV_COMAND";

export const SET_COMMANDS = "TERMINAL/SET_COMMANDS";

export const SET_THEME = "APP/SET_THEME";

export const SET_COLOR = "APP/SET_COLOR";

export const SET_FONT = "APP/SET_FONT";
